[package]
name = "VoteDAO"
version = "1.0.0"
authors = []

[addresses]
my_addrx = "0x160c30b861d6e3ac4864903423e6523a2ed873ae1b41132382f699b07ac684ec"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
